
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMA ERROR HOLA QUE TAL\n    S : X QUE TAL\n    \n    X : X COMA HOLA\n      | HOLA\n    \n    empty : \n    '
    
_lr_action_items = {'HOLA':([0,5,],[1,7,]),'COMA':([1,2,7,],[-3,5,-2,]),'TAL':([4,],[6,]),'$end':([3,6,],[0,-1,]),'QUE':([1,2,7,],[-3,4,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'X':([0,],[2,]),'S':([0,],[3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> S","S'",1,None,None,None),
  ('S -> X QUE TAL','S',3,'p_S','holaQueTal.py',47),
  ('X -> X COMA HOLA','X',3,'p_X','holaQueTal.py',53),
  ('X -> HOLA','X',1,'p_X','holaQueTal.py',54),
  ('empty -> <empty>','empty',0,'p_empty','holaQueTal.py',60),
]
